
/**
 * This file defines the database schema for the application
 * to be used with Supabase. It serves as documentation and
 * can be used to generate types.
 */

/**
 * Users Table
 * Stores user authentication and profile information
 */
export type Users = {
  id: string;                  // UUID, primary key, generated by Supabase Auth
  email: string;               // User email, unique
  name: string;                // User's display name
  role: 'user' | 'consultant' | 'admin' | 'owner';  // User role
  profile_image: string | null; // URL to profile image
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Consultants Table
 * Extends Users table with consultant-specific information
 */
export type Consultants = {
  id: string;                  // UUID, foreign key to users.id
  specialization: string[];    // Array of consultant specializations
  languages: string[];         // Array of languages the consultant speaks
  location: string;            // Consultant location
  bio: string;                 // Consultant biography/description
  rating: number;              // Average rating (1-5)
  review_count: number;        // Total number of reviews
  hourly_rate: number;         // Consultant's hourly rate
  paypal_email: string;        // Consultant's PayPal email for receiving payments
  available: boolean;          // Whether consultant is currently available
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Stories Table
 * Stores mental health stories/blogs
 */
export type Stories = {
  id: string;                  // UUID, primary key
  title: string;               // Story title
  snippet: string;             // Brief summary/preview of the story
  content: string;             // Full story content
  cover_image: string;         // URL to cover image
  author_id: string;           // Foreign key to users.id
  published_at: string;        // Publication timestamp
  tags: string[];              // Array of tags
  tag_type: 'mental' | 'control' | 'drugs' | 'life' | 'anxiety' | 'depression';  // Primary tag type
  is_featured: boolean;        // Whether story is featured on homepage
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Chat Threads Table
 * Stores conversation threads between users and consultants
 */
export type ChatThreads = {
  id: string;                  // UUID, primary key
  user_id: string;             // Foreign key to users.id (regular user)
  consultant_id: string;       // Foreign key to users.id (consultant)
  last_message_at: string;     // Timestamp of last message
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Chat Messages Table
 * Stores individual messages within chat threads
 */
export type ChatMessages = {
  id: string;                  // UUID, primary key
  thread_id: string;           // Foreign key to chat_threads.id
  sender_id: string;           // Foreign key to users.id
  content: string;             // Message content
  read: boolean;               // Whether message has been read
  created_at: string;          // Timestamp, auto-generated
}

/**
 * Sessions Table
 * Stores booked consultation sessions
 */
export type Sessions = {
  id: string;                  // UUID, primary key
  user_id: string;             // Foreign key to users.id (regular user)
  consultant_id: string;       // Foreign key to users.id (consultant)
  start_time: string;          // Session start time
  end_time: string;            // Session end time
  status: 'scheduled' | 'completed' | 'cancelled'; // Session status
  notes: string | null;        // Session notes
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Transactions Table
 * Stores payment transactions for consultations
 */
export type Transactions = {
  id: string;                  // UUID, primary key
  session_id: string | null;   // Foreign key to sessions.id
  user_id: string;             // Foreign key to users.id (who paid)
  consultant_id: string;       // Foreign key to users.id (who received payment)
  amount: number;              // Payment amount
  currency: string;            // Currency code (e.g., 'USD')
  status: 'pending' | 'completed' | 'failed' | 'refunded'; // Transaction status
  payment_method: string;      // How payment was made (e.g., 'credit_card', 'paypal')
  payment_id: string | null;   // External payment processor ID
  description: string;         // Transaction description
  created_at: string;          // Timestamp, auto-generated
}

/**
 * Consultant Availability Table
 * Stores available time slots for consultants
 */
export type ConsultantAvailability = {
  id: string;                  // UUID, primary key
  consultant_id: string;       // Foreign key to users.id
  day_of_week: number;         // 0-6 (Sunday-Saturday)
  start_time: string;          // Time format (HH:MM)
  end_time: string;            // Time format (HH:MM)
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}

/**
 * Reviews Table
 * Stores reviews for consultants
 */
export type Reviews = {
  id: string;                  // UUID, primary key
  user_id: string;             // Foreign key to users.id (reviewer)
  consultant_id: string;       // Foreign key to users.id (consultant being reviewed)
  session_id: string;          // Foreign key to sessions.id
  rating: number;              // Rating (1-5)
  comment: string | null;      // Review comment
  created_at: string;          // Timestamp, auto-generated
  updated_at: string;          // Timestamp, auto-updated
}
