// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qodjhenqguamihndrvct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZGpoZW5xZ3VhbWlobmRydmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDE0NjEsImV4cCI6MjA2MDYxNzQ2MX0.Feq8B-Cnl0KdZifE1o-_Q2c9rPGWQ5CU_Qd90hgtNqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);